### ISSUE TITLE
Add tick and todo list for registered users

### ISSUE THREAD

**Issue by juangallostra** [javigallostra/RocoLib#34]
## Description

Enable registered users to have a personal TODO list so that they can track their projects and mark them as complete when done. This feature should only be visible to registered users.

### TO DO List

- [x] Add tick list to user model
- [x] Load and store user ticklist
- [x] Add ticklist page (login protected) - should be possible to navigate to problem. **TO DO**: Back button should return to ticklist
- [x] Enable adding a problem to the ticklist
- [x] Enable deleting a problem from the ticklist
- [x] Enable marking a problem from the ticklist as done
- [ ] Add log view (login protected) <- Add `date_climbed` to ticklist problem data model? (Add to new issue)
- [x] Add filter to separate done from undone problems

**Comment by juangallostra** [comment]
- [ ] Add tick list to user model
- [ ] Load and store user ticklist
- [ ] Add ticklist page (login protected)
- [ ] Enable adding a problem to the ticklist
- [ ] Enable deleting a problem from the ticklist
- [ ] Enable marking a problem from the ticklist as done
- [ ] Add log view (login protected)

**Comment by juangallostra** [comment]
Closing as per PR #40
